# Generated by Django 4.2.7 on 2025-05-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, help_text='닉네임(중복 가능, 선택 입력)', max_length=150, null=True),
        ),
    ]
