# Generated by Django 4.2.7 on 2025-06-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', '관리자'), ('STORE_OWNER', '매장 관리자'), ('USER', '일반 사용자'), ('GUEST', '게스트 사용자')], default='USER', max_length=20),
        ),
    ]
