# Generated by Django 4.2.7 on 2025-05-26 05:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='공지사항 제목 (최소 5자 이상)', max_length=200, validators=[django.core.validators.MinLengthValidator(5)])),
                ('content', models.TextField(help_text='공지사항 내용 (최소 10자 이상)', validators=[django.core.validators.MinLengthValidator(10)])),
                ('notice_type', models.CharField(choices=[('GENERAL', '전체 공지사항'), ('MEMBER_ONLY', '회원 전용 공지사항')], default='GENERAL', help_text='공지사항 대상 구분', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', '낮음'), ('NORMAL', '보통'), ('HIGH', '높음'), ('URGENT', '긴급')], default='NORMAL', help_text='공지사항 중요도', max_length=10)),
                ('is_published', models.BooleanField(default=True, help_text='공지사항 공개 여부')),
                ('is_pinned', models.BooleanField(default=False, help_text='상단 고정 여부')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='조회수')),
                ('attachment', models.FileField(blank=True, help_text='첨부파일 (선택사항)', null=True, upload_to='notice_attachments/')),
                ('start_date', models.DateTimeField(blank=True, help_text='공지 시작일 (설정하지 않으면 작성일부터 공개)', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='공지 종료일 (설정하지 않으면 무기한 공개)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정 시간')),
                ('author', models.ForeignKey(help_text='공지사항 작성자', on_delete=django.db.models.deletion.CASCADE, related_name='notices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '공지사항',
                'verbose_name_plural': '공지사항들',
                'db_table': 'notices',
                'ordering': ['-is_pinned', '-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoticeReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='notices.notice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_read_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '공지사항 읽음 상태',
                'verbose_name_plural': '공지사항 읽음 상태들',
                'db_table': 'notice_read_statuses',
                'indexes': [models.Index(fields=['user', 'notice'], name='notice_read_user_id_b1606b_idx'), models.Index(fields=['read_at'], name='notice_read_read_at_82311c_idx')],
                'unique_together': {('user', 'notice')},
            },
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['notice_type', 'is_published'], name='notices_notice__311448_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['is_pinned', 'priority'], name='notices_is_pinn_1edc97_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['created_at'], name='notices_created_34a096_idx'),
        ),
    ]
