# Generated by Django 4.2.7 on 2025-05-27 06:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='target_users',
            field=models.ManyToManyField(blank=True, help_text='공지 대상 회원(비어있으면 전체 회원)', related_name='target_notices', to=settings.AUTH_USER_MODEL),
        ),
    ]
