# Generated by Django 4.2.7 on 2025-05-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_notice_target_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice_type',
            field=models.CharField(choices=[('GENERAL', '전체 공지사항'), ('STORE_MANAGER', '매장관리자 공지사항'), ('MEMBER_ONLY', '일반회원 공지사항')], default='GENERAL', help_text='공지사항 대상 구분', max_length=20),
        ),
    ]
