# Generated by Django 4.2.7 on 2025-05-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0003_alter_notice_notice_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-z_order', '-is_pinned', '-priority', '-created_at'], 'verbose_name': '공지사항', 'verbose_name_plural': '공지사항들'},
        ),
        migrations.AddField(
            model_name='notice',
            name='z_order',
            field=models.IntegerField(default=0, help_text='표시 우선순위 (숫자가 클수록 상단에 표시)'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['z_order', 'is_pinned'], name='notices_z_order_1a6ec8_idx'),
        ),
    ]
