# Generated by Django 4.2.7 on 2025-04-24 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='qr_code',
        ),
    ]
