# Generated by Django 4.2.7 on 2025-04-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_remove_seat_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='max_seats',
            field=models.IntegerField(default=0, verbose_name='총 좌석권 수량'),
        ),
    ]
