# Generated by Django 4.2.7 on 2025-05-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_remove_max_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='max_seats',
        ),
        migrations.RemoveField(
            model_name='tournamentregistration',
            name='seat',
        ),
        migrations.AddField(
            model_name='tournament',
            name='ticket_quantity',
            field=models.IntegerField(default=100, verbose_name='좌석권 수량'),
        ),
        migrations.AddField(
            model_name='tournamentregistration',
            name='has_ticket',
            field=models.BooleanField(default=True, verbose_name='좌석권 보유 여부'),
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
