# Generated by Django 4.2.7 on 2025-05-14 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_rename_ticket_quantity_tournament_max_seats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='max_seats',
            new_name='ticket_quantity',
        ),
    ]
