# Generated by Django 4.2.7 on 2025-05-27 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0001_initial'),
        ('tournaments', '0007_rename_max_seats_tournament_ticket_quantity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tournamentregistration',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='store',
        ),
        migrations.AddField(
            model_name='tournamentregistration',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_registrations', to='stores.store', verbose_name='참가 매장'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='tournamentregistration',
            unique_together={('tournament', 'user', 'store')},
        ),
    ]
