# Generated by Django 4.2.7 on 2025-05-27 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_alter_tournamentregistration_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TournamentRegistration',
        ),
    ] 