# Generated by Django 4.2.7 on 2025-06-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_tournamentplayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='buy_in',
            field=models.IntegerField(default=1, verbose_name='바이인(필요 좌석권 수)'),
        ),
    ]
