# Generated by Django 4.2.7 on 2025-06-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0011_change_buy_in_to_integer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tournamentplayer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tournamentplayer',
            name='status',
            field=models.CharField(choices=[('ACTIVE', '활성'), ('USED', '사용됨'), ('CANCELLED', '취소됨')], default='ACTIVE', max_length=20, verbose_name='참가 상태'),
        ),
    ]
