# Generated by Django 4.2.7 on 2025-05-27 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0007_rename_max_seats_tournament_ticket_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='좌석권 ID')),
                ('status', models.CharField(choices=[('ACTIVE', '활성'), ('USED', '사용됨'), ('EXPIRED', '만료됨'), ('CANCELLED', '취소됨')], default='ACTIVE', max_length=20)),
                ('source', models.CharField(choices=[('PURCHASE', '구매'), ('REWARD', '보상'), ('GIFT', '선물'), ('ADMIN', '관리자 지급')], default='PURCHASE', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='금액')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='사용 시간')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='만료 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('memo', models.TextField(blank=True, null=True, verbose_name='메모')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_tickets', to='tournaments.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '좌석권',
                'verbose_name_plural': '좌석권들',
                'db_table': 'seat_tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeatTicketTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('GRANT', '지급'), ('USE', '사용'), ('EXPIRE', '만료'), ('CANCEL', '취소'), ('REFUND', '환불')], max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reason', models.TextField(blank=True, null=True, verbose_name='거래 사유')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_transactions', to=settings.AUTH_USER_MODEL)),
                ('seat_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='seats.seatticket')),
            ],
            options={
                'verbose_name': '좌석권 거래내역',
                'verbose_name_plural': '좌석권 거래내역들',
                'db_table': 'seat_ticket_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSeatTicketSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_tickets', models.IntegerField(default=0, verbose_name='활성 좌석권 수')),
                ('used_tickets', models.IntegerField(default=0, verbose_name='사용된 좌석권 수')),
                ('total_tickets', models.IntegerField(default=0, verbose_name='총 좌석권 수')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_summaries', to='tournaments.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자 좌석권 요약',
                'verbose_name_plural': '사용자 좌석권 요약들',
                'db_table': 'user_seat_ticket_summaries',
                'unique_together': {('user', 'tournament')},
            },
        ),
    ]
