# Generated by Django 4.2.7 on 2025-05-27 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        ('seats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatticket',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seat_tickets', to='stores.store', verbose_name='지급 매장'),
            preserve_default=False,
        ),
    ]
