# Generated by Django 4.2.7 on 2025-05-27 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        ('seats', '0002_seatticket_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatticket',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_tickets', to='stores.store', verbose_name='매장'),
        ),
    ]
