# Generated by Django 4.2.7 on 2025-05-27 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        ('tournaments', '0009_delete_tournamentregistration'),
        ('seats', '0003_alter_seatticket_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentTicketDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_quantity', models.IntegerField(help_text='본사에서 매장에 분배한 좌석권 수량', verbose_name='분배량')),
                ('remaining_quantity', models.IntegerField(help_text='매장에서 현재 보유하고 있는 좌석권 수량', verbose_name='보유수량')),
                ('distributed_quantity', models.IntegerField(default=0, help_text='매장에서 회원들에게 배포한 좌석권 수량', verbose_name='배포수량')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일자')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일자')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='메모')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_distributions', to='stores.store', verbose_name='매장')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_distributions', to='tournaments.tournament', verbose_name='토너먼트')),
            ],
            options={
                'verbose_name': '토너먼트 좌석권 분배',
                'verbose_name_plural': '토너먼트 좌석권 분배들',
                'db_table': 'tournament_ticket_distributions',
                'ordering': ['-created_at'],
                'unique_together': {('tournament', 'store')},
            },
        ),
    ]
