# Generated by Django 4.2.7 on 2025-05-28 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_close_time_store_manager_name_and_more'),
        ('seats', '0004_tournamentticketdistribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatticket',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seat_tickets', to='stores.store', verbose_name='매장'),
        ),
    ]
