# Generated by Django 4.2.7 on 2025-05-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='close_time',
            field=models.TimeField(blank=True, null=True, verbose_name='마감 시간'),
        ),
        migrations.AddField(
            model_name='store',
            name='manager_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='매니저 이름'),
        ),
        migrations.AddField(
            model_name='store',
            name='manager_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='매니저 연락처'),
        ),
        migrations.AddField(
            model_name='store',
            name='max_capacity',
            field=models.PositiveIntegerField(default=50, verbose_name='최대 수용 인원'),
        ),
        migrations.AddField(
            model_name='store',
            name='open_time',
            field=models.TimeField(blank=True, null=True, verbose_name='오픈 시간'),
        ),
        migrations.AddField(
            model_name='store',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='매장 전화번호'),
        ),
        migrations.AlterField(
            model_name='store',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='store_images/', verbose_name='매장 이미지'),
        ),
    ]
