# Generated by Django 4.2.7 on 2025-07-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_recreate_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='is_main_tournament',
            field=models.BooleanField(default=False, help_text='메인 토너먼트 배너로 사용할지 여부를 결정합니다.', verbose_name='메인 토너먼트 배너'),
        ),
    ]
