# Generated by Django 4.2.7 on 2025-07-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_banner_is_main_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='is_store_gallery',
            field=models.BooleanField(default=False, help_text='인기 스토어 갤러리에 표시될 배너인지 여부를 결정합니다.', verbose_name='인기 스토어 갤러리 배너'),
        ),
    ]
