# Generated by Django 4.2.7 on 2025-07-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_add_is_store_gallery_to_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='is_main_selected',
            field=models.BooleanField(default=False, help_text='메인 토너먼트 배너 중에서 실제로 메인에 표시되는 배너인지 여부를 결정합니다.', verbose_name='메인 선택 배너'),
        ),
    ]
