# Generated by Django 4.2.7 on 2025-07-13 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_banner_is_main_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='stores.store'),
        ),
    ]
